reader:
  kafka:
    bootstrap_servers: 'localhost:9092'
    topic: 'mentor_cruise'
    group_id: 'data_processing_group'
    watermark_time_seconds: 300
    window_size_in_seconds: 60

writer:
  iceberg:
    catalog: 'mentor_cruise'
    namespace: 'nessie'
    nessie_server_uri : "http://localhost:19120/api/v2"
    warehouse_bucket : "/tmp/warehouse"

  file:
    format: 'parquet'
    path: 'output/'
    partition_by: 'creation_date'



