file_writer_config:
    output_file_dir: "/tmp/mentor_cruise/data_generation"
    output_file_name: "input_data.json",
    serialization_format: "ndjson"

kafka_config:
    bootstrap_servers: "localhost:9092"
    topic: "mentor_cruise_data"
    group_id: "data_generation_group",
    serialization_format: "avro"
