writer:
    file:
        output_file_dir: "/tmp/mentor_cruise/data_generation"
        output_file_name: "input_data.jsonl"
        serialization_format: "ndjson"

    kafka:
        bootstrap_servers: "localhost:9092"
        topic: "mentor_cruise"
        serialization_format: "json"
